modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="grimsoul_logo.png"
authors="xTri6"
credits="Made by xTri6 for the Nine Craft modpack."
description='''
Mob farming from early game to endgame: the Reaper Block, Reaper's Lantern, Spawner, Generator,
Energy Cell, Soul Cards and the Virtualization Chamber, all in one mod.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
